


namespace control{
	class GameLoop{

		//player
		//camera
		
		//collision map

		//map ?

		//set of pointers to:
		//enemies -> class enemy derives from entity
		//  - move() : acording to a path generated by the collision map
		//  - 
		//walls   -> class walls derives from entity
		//pickups/gameevents -> class pickups derives from entity

		//methods

		//next_frame(float delta_time)

	};



}